branch-defaults:
  dev:
    environment: minimal-beanstalk
  eb-deployment:
    environment: minimal-beanstalk
  master:
    environment: minimal-beanstalk
    group_suffix: null
global:
  application_name: minimal-beanstalk
  branch: null
  default_ec2_keyname: minimal-beanstalk
  default_platform: PHP 8.0
  default_region: us-west-2
  include_git_submodules: true
  sc: git
  workspace_type: Application
